### ISSUE TITLE
Links within the documentation are not working

### ISSUE THREAD

**Issue by brunocamps** [ibm-cloud-docs/personality-insights#87]
For instance, the links in the following section are not working:

https://github.com/ibm-cloud-docs/personality-insights/blob/master/extraversion.md

**Comment by SirSpidey** [comment]
@brunocamps if you're trying to read the documentation from within Github, the links won't work. You can read that page in IBM Cloud at https://cloud.ibm.com/docs/personality-insights?topic=personality-insights-extraversion

**Comment by jeffpk62** [comment]
Thanks, @SirSpidey.  I just tested the link in that section in the public docs, and it appears to be fine.  @brunocamps, if you find any problem links in the published docs, please let us know.  Thank you!
