### ISSUE TITLE
Does personality insight API support simplified Chinese?

### ISSUE THREAD

**Issue by alfonsocheng1025** [ibm-cloud-docs/personality-insights#88]
Hi, I'm trying use personality insight API to get personality and value scores from social media posts in simplified Chinese. I find there do support Chinese in the API document, but I get the error when I doing so. Error info is {"code":400,"sub_code":"C00001","error":"The language you requested, zh-cn, is not supported. Languages supported: en,es,ja,ar,ko."}. Can anyone figure this out? If so, what is the code? THX!

**Comment by jeffpk62** [comment]
@alfonsocheng1025 You can request that the service respond in Simplified Chinese, but the service does not accept simplified Chinese as input text.  This section provides more information:  https://cloud.ibm.com/docs/personality-insights?topic=personality-insights-input#languages-input.

**Comment by alfonsocheng1025** [comment]
> @alfonsocheng1025 You can request that the service respond in Simplified Chinese, but the service does not accept simplified Chinese as input text. This section provides more information: https://cloud.ibm.com/docs/personality-insights?topic=personality-insights-input#languages-input.
> 
> You can consider translating the input from Chinese to one of the five supported input languages (English, Spanish, Japanese, Arabic, or Korean).

Thank you! Another question is what's the differences between "Content-Language" and "Accept-Language"? I cannot actually get what you mean by "service respond in simplified Chinese".

**Comment by jeffpk62** [comment]
@alfonsocheng1025 `Content-Language` is the header that you use to indicate the language of the data you are passing to the service.  `Accept-Language` is the header you use to indicate the language of the response that you want from the service.  So you can pass request data in one language and get personality profile results in a different language.  You can get response results from the service in Chinese, but you can't pass Chinese input data.

**Comment by alfonsocheng1025** [comment]
got it. appreciate~

**Comment by jeffpk62** [comment]
You're very welcome.
